name: tsurugidb-CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: [self-hosted, docker]
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:${{ matrix.os }}
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
        - ${{ vars.gradle_cache_dir }}:/root/.gradle
    defaults:
      run:
        shell: bash
    env:
      CCACHE_CONFIGPATH: ${{ vars.ccache_dir }}/ccache.conf
      CCACHE_DIR: ${{ vars.ccache_dir }}/${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate_Install_Archive
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            export TG_RELEASE_TSURUGI_VERSION=${GITHUB_REF_NAME}
          fi
          ./dist/install/generate-install-archive.sh

      - name: Install
        run: |
          mkdir work-install
          mkdir build-install-test

          cd work-install
          tar xf ../tsurugidb-*.tar.gz --strip-components 1
          ./install.sh --prefix=${GITHUB_WORKSPACE}/build-install-test --symbolic --skip=harinoki
        env:
          TG_COMMON_CMAKE_BUILD_OPTIONS: '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache'

      - name: Upload_Install_Archive
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: install-archive
          path: tsurugidb-*.tar.gz

      - name: Show_Tsurugi_Version
        if: matrix.os == 'ubuntu-22.04'
        run: |
          cd work-install
          cat BUILDINFO.md >> ${GITHUB_STEP_SUMMARY}

      - name: Generate_Binary_Archive
        if: matrix.os == 'ubuntu-22.04' && (contains(github.ref, '/tags/') || contains(github.ref, '/heads/master'))
        run: |
          cd build-install-test
          TSURUGI_VERSION=$(grep -oP '(?<=^TSURUGI_VERSION:).*' tsurugi/BUILDINFO.md)
          tar -czf ../tsurugidb-bin-${{ matrix.os }}-${TSURUGI_VERSION}.tar.gz *

      - name: Upload_Binary_Archive
        if: matrix.os == 'ubuntu-22.04' && (contains(github.ref, '/tags/') || contains(github.ref, '/heads/master'))
        uses: actions/upload-artifact@v4
        with:
          name: binary-archive-${{ matrix.os }}
          path: tsurugidb-bin-*.tar.gz

  Test:
    uses: ./.github/workflows/ci-test-modules.yml
    secrets: inherit
    permissions:
      checks: write

  Check:
    runs-on: [self-hosted, docker]
    timeout-minutes: 10
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Diff_Proto
        run: |
          ./.github/workflows/scripts/diff-proto.sh
